# Generated by Django 5.1.7 on 2025-04-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Age',
                'verbose_name_plural': 'Ages',
            },
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='age_range',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='age_range',
            field=models.ManyToManyField(related_name='products', to='products.agemodel', verbose_name='age_range'),
        ),
    ]
