# Generated by Django 5.1.7 on 2025-04-13 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_agemodel_remove_productmodel_age_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeModelAdmin',
            fields=[
                ('agemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.agemodel')),
            ],
            bases=('products.agemodel',),
        ),
        migrations.RemoveField(
            model_name='agemodel',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='agemodel',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='agemodel',
            name='name_uz',
        ),
    ]
