# Generated by Django 5.1.7 on 2025-04-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_agemodeladmin_remove_agemodel_name_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgeModelAdmin',
        ),
    ]
