# Generated by Django 5.1.7 on 2025-03-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_bannermodel_productmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='extra_images',
            field=models.JSONField(default=list, verbose_name='extra images'),
        ),
    ]
