# Generated by Django 5.1.7 on 2025-04-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_agemodeladmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='age_range',
            new_name='agerange',
        ),
    ]
