# Generated by Django 5.1.7 on 2025-04-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_age_range_productmodel_agerange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='agerange',
            new_name='age_range',
        ),
    ]
