# Generated by Django 5.1.7 on 2025-03-20 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_categorymodel_colormodel_name_af_colormodel_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannermodel',
            name='description_af',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ar_dz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ast',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_az',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_be',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_bg',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_bn',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_br',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_bs',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ca',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ckb',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_cs',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_cy',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_da',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_de',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_dsb',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_el',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_en_au',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_en_gb',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_eo',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_es',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_es_ar',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_es_co',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_es_mx',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_es_ni',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_es_ve',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_et',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_eu',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_fi',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_fy',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ga',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_gd',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_gl',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_he',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_hi',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_hr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_hsb',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_hu',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_hy',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ia',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ig',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ind',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_io',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_is',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_it',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ja',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ka',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_kab',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_km',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_kn',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ko',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_lb',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_lt',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_lv',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_mk',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ml',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_mn',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_mr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ms',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_my',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_nb',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ne',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_nl',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_nn',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_os',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_pa',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_pl',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_pt',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_pt_br',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ro',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_sk',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_sl',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_sq',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_sr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_sr_latn',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_sv',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_sw',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ta',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_te',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_tg',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_th',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_tk',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_tt',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_udm',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ug',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_ur',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_vi',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_zh_hans',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='description_zh_hant',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.productmodel')),
            ],
        ),
    ]
