# Generated by Django 5.1.7 on 2025-04-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_agerange_productmodel_age_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='age_range',
            new_name='agerange',
        ),
    ]
