# Generated by Django 5.1.7 on 2025-04-15 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_age_range_productmodel_agerange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='cart'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='wishlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='wishlist'),
        ),
    ]
