# Generated by Django 5.1.7 on 2025-03-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_commentmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='image',
        ),
    ]
