# Generated by Django 5.1.7 on 2025-03-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productmodel_extra_images_productimagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='price'),
        ),
    ]
