# Generated by Django 5.1.7 on 2025-03-30 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productmodel_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='sku',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='wishlist'),
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='color',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='is_available'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='long_description',
            field=models.TextField(verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='long_description_en',
            field=models.TextField(null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='long_description_ru',
            field=models.TextField(null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='long_description_uz',
            field=models.TextField(null=True, verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='short_description',
            field=models.TextField(verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='short_description_uz',
            field=models.TextField(null=True, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='color',
            field=models.ManyToManyField(related_name='products', to='products.colormodel', verbose_name='color'),
        ),
    ]
