# Generated by Django 5.1.7 on 2025-04-03 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_productmodel_age_range_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='cart',
            field=models.ManyToManyField(related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='cart'),
        ),
    ]
