# Generated by Django 5.1.7 on 2025-04-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productmodel_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantity'),
        ),
    ]
