# Generated by Django 5.1.7 on 2025-04-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productmodel_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='quantity',
        ),
    ]
