# Generated by Django 5.1.7 on 2025-04-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_productmodel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(default=0, verbose_name='price'),
        ),
    ]
