# Generated by Django 5.1.7 on 2025-04-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productmodel_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='price',
            new_name='get_price',
        ),
    ]
