# Generated by Django 5.1.7 on 2025-04-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rename_price_productmodel_get_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='get_price',
            new_name='price',
        ),
    ]
